### ISSUE TITLE
Local Saves

### ISSUE THREAD

**Issue by lsultana98** [linuxserver/docker-emulatorjs#2]
I was wondering if it was currently possible, or in the works for there to be a central location for save files. Rather than it being browser specific. Example for the use case would be if I wanted to play a ROM on multiple devices and use the same save.

Really liking this project so far.

**Comment by thelamer** [comment]
The entire premise of this application is to be essentially server less, the backend is only used as a helper so people without any underlying knowledge can generate a functional set of frontend files.

**Comment by lsultana98** [comment]
Fair enough, no problem then. Was looking for an application exactly like this, only draw back was the saves. Thanks for the reply mate.

**Comment by thelamer** [comment]
The application is open source, and the frontend uses browserfs.
It has a global fs object just like a nodejs application would. There is nothing to stop anyone from dumping the directory contents of the browserfs mount under `/home/web_user/retroarch/userdata` folder. From there it can be downloaded as a tarball or pushed to any external server.

There are a little more docs here https://github.com/linuxserver/libretrojs about interacting with the module that is running to call saves, from there you just dump the resulting save somewhere.

Keep in mind this is open source, just because I don't want to do it, doesn't mean someone else can't.

**Comment by richardphi1618** [comment]
+1 for this feature

**Comment by thelamer** [comment]
In the latest version there is now a file explorer icon in the top left of the interface, this allows you to manage the browser storage and download/upload full backups. While not cloud saving it does allow a user to migrate saves around to different devices.

**Comment by 4lexKidd** [comment]
Just as a side note because this is very badly documented:
In the current version it IS possible to have local save files on the server.
For that to achieve you have to create a profile on the management-page (User + PW).
After creating that profile on the gaming/overview page in the upper left corner, there is a button/link to the file system. There you can log-in with the created profile credentials.

Using this allows you to upload your locally created saves & savestates to the server (and potentially backing them up) and to change the device/browser, login again and import from server to enjoy the same saves/savestates as created on the other machine.
Sadly this feature was quite silently added and there is afaik no or very spare information on that. Stumpled on that Info on reddit as a user mentioned it.

For me, that is a complete gamechanger as of having emulatorjs self-hostet for my family.

**Comment by looklook827** [comment]
> Just as a side note because this is very badly documented: In the current version it IS possible to have local save files on the server. For that to achieve you have to create a profile on the management-page (User + PW). After creating that profile, on the gaming/overview page in the upper left corner, there is a button/link to the file system. There you can log-in with the created profile credentials.
> 
> Using this allows you to download serversided saves to local device or upload your locally created saves & savestates to the server (and potentially backing them up) and to change the device/browser, login again and import from server to enjoy the same saves/savestates as created on the other machine. Sadly this feature was quite silently added and there is afaik no or very spare information on that. Stumpled on that Info on reddit as a user mentioned it.
> 
> For me, that is a complete gamechanger as of having emulatorjs self-hostet for my family.

Thank you so much for telling it!!! This is an life-changing feature!!!

**Comment by LordZeuss** [comment]
> Just as a side note because this is very badly documented: In the current version it IS possible to have local save files on the server. For that to achieve you have to create a profile on the management-page (User + PW). After creating that profile, on the gaming/overview page in the upper left corner, there is a button/link to the file system. There you can log-in with the created profile credentials.
> 
> Using this allows you to download serversided saves to local device or upload your locally created saves & savestates to the server (and potentially backing them up) and to change the device/browser, login again and import from server to enjoy the same saves/savestates as created on the other machine. Sadly this feature was quite silently added and there is afaik no or very spare information on that. Stumpled on that Info on reddit as a user mentioned it.
> 
> For me, that is a complete gamechanger as of having emulatorjs self-hostet for my family.

Awesome! Are you able to provide a step by step on how you load the save files? I was able to create a user profile, login, and upload a save file in the same folder as retroarch.cfg but I'm not sure how to load them or anything. Thanks!

**Comment by Dkirk25** [comment]
> Just as a side note because this is very badly documented: In the current version it IS possible to have local save files on the server. For that to achieve you have to create a profile on the management-page (User + PW). After creating that profile, on the gaming/overview page in the upper left corner, there is a button/link to the file system. There you can log-in with the created profile credentials.
> 
> Using this allows you to download serversided saves to local device or upload your locally created saves & savestates to the server (and potentially backing them up) and to change the device/browser, login again and import from server to enjoy the same saves/savestates as created on the other machine. Sadly this feature was quite silently added and there is afaik no or very spare information on that. Stumpled on that Info on reddit as a user mentioned it.
> 
> For me, that is a complete gamechanger as of having emulatorjs self-hostet for my family.

Not all heros wear capes

**Comment by Dkirk25** [comment]
> > Just as a side note because this is very badly documented: In the current version it IS possible to have local save files on the server. For that to achieve you have to create a profile on the management-page (User + PW). After creating that profile, on the gaming/overview page in the upper left corner, there is a button/link to the file system. There you can log-in with the created profile credentials.
> > Using this allows you to download serversided saves to local device or upload your locally created saves & savestates to the server (and potentially backing them up) and to change the device/browser, login again and import from server to enjoy the same saves/savestates as created on the other machine. Sadly this feature was quite silently added and there is afaik no or very spare information on that. Stumpled on that Info on reddit as a user mentioned it.
> > For me, that is a complete gamechanger as of having emulatorjs self-hostet for my family.
> 
> Awesome! Are you able to provide a step by step on how you load the save files? I was able to create a user profile, login, and upload a save file in the same folder as retroarch.cfg but I'm not sure how to load them or anything. Thanks!

When you save your state, make sure to back to the file system page on the top right and click the " push up to server" button. Then you can go on your other devices and click the "pull down from server" button. Then everything should be in sync
